source("read_and_clean.R")
png("plot3.png")
plot(sub$DateTime, sub$Sub_metering_1, type = "l", xlab = "", ylab = "Energy sub metering")
lines(x = sub$DateTime, y = sub$Sub_metering_2, col = "red")
lines(x = sub$DateTime, y = sub$Sub_metering_3, col = "blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty = c(1,1,1), col = c("black","red","blue"))
invisible(dev.off())