source("read_and_clean.R")
png("plot4.png")
par(mfrow = c(2, 2))
plot(sub$DateTime, sub$Global_active_power, type = "l", xlab = "", ylab = "Global Active Power")
plot(sub$DateTime, sub$Voltage, type = "l", xlab = "datetime", ylab = "Voltage")
plot(sub$DateTime, sub$Sub_metering_1, type = "l", xlab = "", ylab = "Energy sub metering")
lines(x = sub$DateTime, y = sub$Sub_metering_2, col = "red")
lines(x = sub$DateTime, y = sub$Sub_metering_3, col = "blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty = c(1,1,1), col = c("black","red","blue"), bty="n")
plot(sub$DateTime, sub$Global_reactive_power, type = "l", xlab = "datetime", ylab = "Global_reactive_power")
invisible(dev.off())